version: '3.4'
services:
  instance:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        uid: ${uid}
    user: imio
    ports:
      - "8080:8080"
    volumes:
      - .:/home/imio/intranet
    environment:
      - ENV=dev
      - DOMAINS=localhost
    command: fg
