ARG uid="1000"
FROM docker-staging.imio.be/intranet/cache:${uid}
RUN mkdir /home/imio/imio-intranet
COPY *.cfg /home/imio/imio-intranet/
COPY *.sh /home/imio/imio-intranet/
COPY Makefile /home/imio/imio-intranet/
RUN chown imio:imio -R /home/imio/imio-intranet/
WORKDIR /home/imio/imio-intranet
USER imio
RUN ./bootstrap.sh -c prod.cfg
ENV HOSTNAME_HOST local
ENV PROJECT_ID intranet-imio
