FROM docker-staging.imio.be/intranet/cache:latest
ARG uid="1000"
RUN usermod -u ${uid} imio
RUN mkdir /home/imio/intranet
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
RUN chown imio:imio /docker-entrypoint.sh
RUN chown imio:imio -R /home/imio/intranet
WORKDIR /home/imio/intranet
ENTRYPOINT ["/docker-entrypoint.sh"]
