version: '3.4'
services:
  instance:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        uid: ${uid}
    user: imio
    ports:
      - "8080:8080"
    # volumes:
    #   - ./src:/home/imio/intranet/src
    working_dir: /home/imio/intranet
    environment:
      - ENV=dev
      - DOMAINS=localhost
    command: /home/imio/intranet/bin/instance fg
